name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: CI Check
        run: echo "Cấu trúc thư mục chuẩn. Sẵn sàng deploy lên Vercel thông qua Vercel Dashboard."
