name: CI/CD Pipeline Fashi Template

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  deploy-to-vercel:
    name: Deploy to Vercel
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code từ GitHub
        uses: actions/checkout@v4

      - name: Deploy lên Cloud Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
